# Generated by Django 5.0 on 2023-12-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.TextField(blank=True, null=True)),
                ('resume_link', models.URLField(blank=True, null=True)),
                ('linkedin_profile', models.URLField(blank=True, null=True, verbose_name='LinkedIn профиль')),
                ('github_profile', models.URLField(blank=True, null=True, verbose_name='GitHub профиль')),
                ('twitter_profile', models.URLField(blank=True, null=True, verbose_name='Twitter профиль')),
                ('telegram_username', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram')),
                ('languages', models.ManyToManyField(blank=True, to='portfolio.language', verbose_name='Языки программирования')),
                ('skills', models.ManyToManyField(blank=True, to='portfolio.skill', verbose_name='Навыки')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='project_images/')),
                ('repository_link', models.URLField()),
                ('live_link', models.URLField()),
                ('status', models.CharField(choices=[('developing', 'В разработке'), ('completed', 'Завершен'), ('paused', 'Приостановлен')], default='developing', max_length=20)),
                ('technologies', models.ManyToManyField(to='portfolio.technology')),
            ],
        ),
    ]
