# Generated by Django 5.0 on 2024-01-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_project_image_projectimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка на сертификат')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitter_profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='certificates',
            field=models.ManyToManyField(blank=True, to='portfolio.certificate', verbose_name='Сертификаты'),
        ),
    ]
